// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LemonSqueezy.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MofoTaskAuthor
    {
        /// <summary>
        /// Initializes a new instance of the MofoTaskAuthor class.
        /// </summary>
        public MofoTaskAuthor()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MofoTaskAuthor class.
        /// </summary>
        public MofoTaskAuthor(int? id = default(int?), string name = default(string), string handle = default(string), string link = default(string), IList<MofoTask> mofoTasks = default(IList<MofoTask>))
        {
            Id = id;
            Name = name;
            Handle = handle;
            Link = link;
            MofoTasks = mofoTasks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "handle")]
        public string Handle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "link")]
        public string Link { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mofoTasks")]
        public IList<MofoTask> MofoTasks { get; set; }

    }
}
