// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LemonSqueezy.API.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MofoCommand
    {
        /// <summary>
        /// Initializes a new instance of the MofoCommand class.
        /// </summary>
        public MofoCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MofoCommand class.
        /// </summary>
        public MofoCommand(string command, System.DateTime commandTime, int commandOutputId, string userId, int? id = default(int?), CommandOutput commandOutput = default(CommandOutput), LemonSqueezyUser user = default(LemonSqueezyUser), int? mofoTaskingId = default(int?), MofoTasking mofoTasking = default(MofoTasking), int? mofoId = default(int?))
        {
            Id = id;
            Command = command;
            CommandTime = commandTime;
            CommandOutputId = commandOutputId;
            CommandOutput = commandOutput;
            UserId = userId;
            User = user;
            MofoTaskingId = mofoTaskingId;
            MofoTasking = mofoTasking;
            MofoId = mofoId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public string Command { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandTime")]
        public System.DateTime CommandTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandOutputId")]
        public int CommandOutputId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandOutput")]
        public CommandOutput CommandOutput { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public LemonSqueezyUser User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mofoTaskingId")]
        public int? MofoTaskingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mofoTasking")]
        public MofoTasking MofoTasking { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mofoId")]
        public int? MofoId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Command == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Command");
            }
            if (UserId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserId");
            }
            if (CommandOutput != null)
            {
                CommandOutput.Validate();
            }
            if (User != null)
            {
                User.Validate();
            }
            if (MofoTasking != null)
            {
                MofoTasking.Validate();
            }
        }
    }
}
