// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LemonSqueezy.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MofoTaskingStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MofoTaskingStatus
    {
        [EnumMember(Value = "Uninitialized")]
        Uninitialized,
        [EnumMember(Value = "Tasked")]
        Tasked,
        [EnumMember(Value = "Progressed")]
        Progressed,
        [EnumMember(Value = "Completed")]
        Completed,
        [EnumMember(Value = "Aborted")]
        Aborted
    }
    internal static class MofoTaskingStatusEnumExtension
    {
        internal static string ToSerializedValue(this MofoTaskingStatus? value)
        {
            return value == null ? null : ((MofoTaskingStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MofoTaskingStatus value)
        {
            switch( value )
            {
                case MofoTaskingStatus.Uninitialized:
                    return "Uninitialized";
                case MofoTaskingStatus.Tasked:
                    return "Tasked";
                case MofoTaskingStatus.Progressed:
                    return "Progressed";
                case MofoTaskingStatus.Completed:
                    return "Completed";
                case MofoTaskingStatus.Aborted:
                    return "Aborted";
            }
            return null;
        }

        internal static MofoTaskingStatus? ParseMofoTaskingStatus(this string value)
        {
            switch( value )
            {
                case "Uninitialized":
                    return MofoTaskingStatus.Uninitialized;
                case "Tasked":
                    return MofoTaskingStatus.Tasked;
                case "Progressed":
                    return MofoTaskingStatus.Progressed;
                case "Completed":
                    return MofoTaskingStatus.Completed;
                case "Aborted":
                    return MofoTaskingStatus.Aborted;
            }
            return null;
        }
    }
}
