// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LemonSqueezy.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MofoStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MofoStatus
    {
        [EnumMember(Value = "Uninitialized")]
        Uninitialized,
        [EnumMember(Value = "Stage0")]
        Stage0,
        [EnumMember(Value = "Stage1")]
        Stage1,
        [EnumMember(Value = "Stage2")]
        Stage2,
        [EnumMember(Value = "Active")]
        Active,
        [EnumMember(Value = "Lost")]
        Lost,
        [EnumMember(Value = "Exited")]
        Exited,
        [EnumMember(Value = "Disconnected")]
        Disconnected,
        [EnumMember(Value = "Hidden")]
        Hidden
    }
    internal static class MofoStatusEnumExtension
    {
        internal static string ToSerializedValue(this MofoStatus? value)
        {
            return value == null ? null : ((MofoStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MofoStatus value)
        {
            switch( value )
            {
                case MofoStatus.Uninitialized:
                    return "Uninitialized";
                case MofoStatus.Stage0:
                    return "Stage0";
                case MofoStatus.Stage1:
                    return "Stage1";
                case MofoStatus.Stage2:
                    return "Stage2";
                case MofoStatus.Active:
                    return "Active";
                case MofoStatus.Lost:
                    return "Lost";
                case MofoStatus.Exited:
                    return "Exited";
                case MofoStatus.Disconnected:
                    return "Disconnected";
                case MofoStatus.Hidden:
                    return "Hidden";
            }
            return null;
        }

        internal static MofoStatus? ParseMofoStatus(this string value)
        {
            switch( value )
            {
                case "Uninitialized":
                    return MofoStatus.Uninitialized;
                case "Stage0":
                    return MofoStatus.Stage0;
                case "Stage1":
                    return MofoStatus.Stage1;
                case "Stage2":
                    return MofoStatus.Stage2;
                case "Active":
                    return MofoStatus.Active;
                case "Lost":
                    return MofoStatus.Lost;
                case "Exited":
                    return MofoStatus.Exited;
                case "Disconnected":
                    return MofoStatus.Disconnected;
                case "Hidden":
                    return MofoStatus.Hidden;
            }
            return null;
        }
    }
}
